[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.21"   # Override for the solc version (setting this ignores `auto_detect_solc`)
evm_version = "paris"     # to prevent usage of PUSH0, which is not supported on all chains


remappings = [
    'ds-test/=lib/ds-test/src/',
    'solmate/=lib/solmate/src/',
    'forge-std/=lib/forge-std/src/',
    'v3-core/=lib/v3-core/contracts/',
    'v2-core/=lib/v2-core/contracts/',
    'v2-periphery/=lib/v2-periphery/contracts/'
]

fs_permissions = [{ access = "read-write", path = "./"}]

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
